import type { MapLayerDefinition } from "@/shared/types/layers";

export const staticLayers: MapLayerDefinition[] = [
  {
    id: "mining-iup",
    name: "Permit boundaries",
    sub: "ESDM / MOMI",
    description: "IUP permit boundaries from ESDM and MOMI records. Permits inside an AOI are counted in the AOI analysis panel.",
    category: "mining",
    type: "vector",
    defaultVisible: true,
    opacity: 1,
    source: { type: "geojson", url: "/data/mining/iup.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#B4652A",
      "fill-opacity": 0.18,
      "line-color": "#B4652A",
      "line-width": 2,
      "line-dasharray": [5, 3],
    },
  },
  {
    id: "rivers",
    name: "Rivers & watershed",
    description: "River network lines used for proximity analysis (distance to nearest river in the AOI panel).",
    category: "hydrology",
    type: "vector",
    defaultVisible: true,
    opacity: 0.9,
    source: { type: "geojson", url: "/data/hydrology/rivers.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#3FA0AA",
      "line-width": 2.5,
    },
  },
  {
    id: "watersheds",
    name: "Watershed boundaries",
    description: "Watershed (DAS) catchment boundaries, one color per catchment. Large fills — use with low opacity.",
    category: "hydrology",
    type: "vector",
    defaultVisible: false,
    opacity: 0.3,
    source: { type: "geojson", url: "/data/hydrology/watersheds.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#1F7A8C",
      "fill-opacity": 0.1,
      "line-color": "#1F7A8C",
      "line-width": 1.5,
      "line-dasharray": [4, 3],
    },
  },
  {
    id: "drainage",
    name: "Derived drainage",
    sub: "D8 DEMNAS · flow model",
    description: "Stream network derived from DEMNAS via fill-sinks, D8 flow direction and flow accumulation (catchments > ~9 km²). 87 of 90 stream segments align with the BIG reference network — use it for flow context where BIG rivers are incomplete.",
    category: "hydrology",
    type: "vector",
    defaultVisible: false,
    opacity: 0.9,
    source: { type: "geojson", url: "/data/hydrology/drainage.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#7FB8C4",
      "line-width": 1.5,
      "line-dasharray": [2, 2],
    },
  },
  {
    id: "watersheds-derived",
    name: "Derived catchments",
    sub: "D8 DEMNAS · flow model",
    description: "Drainage catchments delineated from the same DEMNAS D8 flow model — every cell of a catchment drains to the same stream mouth. 48 catchments cover ~2,200 km²; each polygon lists its modelled area. Model output, not an official boundary.",
    category: "hydrology",
    type: "vector",
    defaultVisible: false,
    opacity: 0.3,
    source: { type: "geojson", url: "/data/hydrology/watersheds-derived.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#A67C52",
      "fill-opacity": 0.12,
      "line-color": "#A67C52",
      "line-width": 1.5,
      "line-dasharray": [2, 3],
    },
  },
  {
    id: "coastline",
    name: "Coastline",
    description: "Baseline coastline used for distance-to-coast measurement in the AOI analysis panel.",
    category: "coastal",
    type: "vector",
    defaultVisible: false,
    opacity: 0.8,
    source: { type: "geojson", url: "/data/coastal/baseline-coastline.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#B8901E",
      "line-width": 2,
    },
  },
  {
    id: "settlements",
    name: "Settlements",
    description: "Settlement point locations from OSM. Sparse coverage — Taliabu villages are partly unmapped.",
    category: "terrain",
    type: "vector",
    defaultVisible: false,
    opacity: 1,
    source: { type: "geojson", url: "/data/human/settlements.geojson" },
    layerType: "point",
    paint: {
      "circle-radius": 5,
      "circle-color": "#F7F8F1",
      "circle-stroke-color": "#14231D",
      "circle-stroke-width": 1.5,
    },
  },
  {
    id: "settlement-areas",
    name: "Settlement areas",
    description: "Built-up area polygons. Fallback for village footprints where OSM points are missing.",
    category: "terrain",
    type: "vector",
    defaultVisible: false,
    opacity: 0.35,
    source: { type: "geojson", url: "/data/human/settlement-areas.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#C98B55",
      "fill-opacity": 0.18,
      "line-color": "#C98B55",
      "line-width": 1,
    },
  },
  {
    id: "admin-boundary",
    name: "Administrative boundary",
    sub: "Kab. Pulau Taliabu",
    description: "Official administrative boundary of Kabupaten Pulau Taliabu (BIG Satu Peta / RBI).",
    category: "administrative",
    type: "vector",
    defaultVisible: false,
    opacity: 0.6,
    source: { type: "geojson", url: "/data/boundaries/administrative-boundaries.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#3E4C44",
      "line-width": 2,
      "line-dasharray": [6, 3],
    },
  },

  {
    id: "scl",
    name: "Scene Classification",
    sub: "SCL · diagnostic",
    description: "ESA's Sen2Cor scene classification algorithm distinguishes cloudy, clear and water pixels of Sentinel-2 data. Twelve classes are provided, including clouds, vegetation, soils/desert, water and snow. It does not constitute a land cover classification map in a strict sense — diagnostic only.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "scl" },
    legend: [
      { label: "No data", color: "#000000" },
      { label: "Saturated", color: "#FF0000" },
      { label: "Dark area", color: "#2F2F2F" },
      { label: "Cloud shadow", color: "#643200" },
      { label: "Vegetation", color: "#00A000" },
      { label: "Bare soil", color: "#FFE65A" },
      { label: "Water", color: "#0000FF" },
      { label: "Unclassified", color: "#808080" },
      { label: "Cloud medium", color: "#C0C0C0" },
      { label: "Cloud high", color: "#FFFFFF" },
      { label: "Cirrus", color: "#64C8FF" },
      { label: "Snow/ice", color: "#FF96FF" },
    ],
  },
  {
    id: "ndvi",
    name: "NDVI",
    sub: "Vegetation · B08, B04",
    description: "The normalized difference vegetation index is a simple but effective index for quantifying green vegetation — a measure of vegetation health based on how plants reflect light at certain wavelengths. The value range is -1 to 1: negative values (approaching -1) correspond to water, values close to zero (-0.1 to 0.1) to barren rock, sand or snow, low positive values (0.2 to 0.4) to shrub and grassland, and high values (approaching 1) to temperate and tropical rainforests. Displayed raw — use the cloud mask chip to hide cloud/shadow pixels.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "ndvi", maskable: true },
    legend: [
      { label: "-1 → +1", color: "linear-gradient(90deg,#DBDBDB,#FAFACC,#80B347,#004500)" },
    ],
  },
  {
    id: "ndwi",
    name: "NDWI",
    sub: "Water · B03, B08",
    description: "The normalized difference water index is most appropriate for water body mapping. Water bodies have values larger than 0.5, vegetation has smaller values, and built-up features have positive values between zero and 0.2. Cloud shadow can read as water — use the cloud mask for interpretation.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "ndwi", maskable: true },
    legend: [
      { label: "-1 → +1", color: "linear-gradient(90deg,#008000,#FFFFFF,#0000CC)" },
    ],
  },
  {
    id: "mndwi",
    name: "MNDWI",
    sub: "Modified water · B03, B11",
    description: "Modified water index using SWIR (B11) — separates water better than NDWI in turbid or shallow coastal water. Not a standard Copernicus Browser product.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "mndwi", maskable: true },
    legend: [
      { label: "land → water", color: "linear-gradient(90deg,#B38033,#D9D1BF,#8CBFD1,#0D4DA6,#001A73)" },
    ],
  },
  {
    id: "false-color",
    name: "False Color",
    sub: "Analysis · B08, B04, B03",
    description: "A false color composite uses at least one non-visible wavelength to image Earth. The near infrared, red and green composite is very popular and most commonly used to assess plant density and health: plants reflect near infrared and green light while absorbing red, so vegetation appears red, cities and exposed ground grey or tan, and water blue or black.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "false-color", maskable: true },
    legend: [{ label: "Vegetation → red", color: "#C8372D" }],
  },
  {
    id: "bare-soil",
    name: "SWIR",
    sub: "Bare soil/analysis · B12, B11, B04",
    description: "Short wave infrared measurements help estimate how much water is present in plants and soil, as water absorbs SWIR wavelengths. SWIR bands also distinguish cloud types (water vs ice clouds), snow and ice. In this composite vegetation appears in shades of green, soils and built-up areas in various shades of brown, and water black. Newly burned land reflects strongly in SWIR, making it valuable for mapping fire damage, and each rock type reflects SWIR differently, enabling geology mapping. Rendered with highlight compression to brighten bare soil, quarry faces and haul roads against forest.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "bare-soil" },
    legend: [{ label: "Bare soil / built-up", color: "#B38033" }],
  },
  {
    id: "elevation",
    name: "Elevation",
    sub: "DEMNAS · 0.27 arc-s",
    description: "Digital elevation model from BIG DEMNAS (IFSAR/TerraSAR-X/ALOS PALSAR), 66 m per pixel over the analysis window, vertical datum EGM2008. Ocean and no-data pixels are transparent.",
    category: "terrain",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: {
      type: "raster",
      staticUrl: "/data/terrain/elevation.png",
      bbox: [124.2, -2.35, 125.4, -1.15],
    },
    legend: [
      { label: "0 → 1400 m", color: "linear-gradient(90deg,#3E6B4F,#7FA05A,#C9B26A,#9A7B55,#EFEFEF)" },
    ],
  },
  {
    id: "slope",
    name: "Slope",
    sub: "derived · Horn 3×3",
    description: "Terrain slope in degrees, derived from DEMNAS elevation with a Horn 3×3 operator. Steep slopes indicate higher runoff energy and erosion risk below disturbed areas.",
    category: "terrain",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: {
      type: "raster",
      staticUrl: "/data/terrain/slope.png",
      bbox: [124.2, -2.35, 125.4, -1.15],
    },
    legend: [
      { label: "0° → 60°+", color: "linear-gradient(90deg,#2F5D3A,#7FA05A,#D8C25A,#B4652A,#8A2E1F)" },
    ],
  },
  {
    id: "sar",
    name: "SAR (Sentinel-1)",
    sub: "VV, VH · cloud-penetrating",
    description: "Radar backscatter, unaffected by clouds. Tropical forest sits at the sensor noise floor — single-date texture is noisy; interpret diagnostically, not as change.",
    category: "satellite",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "sar" },
  },
];
