import type { MapLayerDefinition } from "@/shared/types/layers";

export const staticLayers: MapLayerDefinition[] = [
  {
    id: "mining-iup",
    name: "Permit boundaries",
    sub: "ESDM / MOMI",
    description: "IUP permit boundaries from ESDM and MOMI records. Permits inside an AOI are counted in the AOI analysis panel.",
    category: "mining",
    type: "vector",
    defaultVisible: true,
    opacity: 1,
    source: { type: "geojson", url: "/data/mining/iup.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#B4652A",
      "fill-opacity": 0.18,
      "line-color": "#B4652A",
      "line-width": 2,
      "line-dasharray": [5, 3],
    },
  },
  {
    id: "rivers",
    name: "Rivers & watershed",
    description: "River network lines used for proximity analysis (distance to nearest river in the AOI panel).",
    category: "hydrology",
    type: "vector",
    defaultVisible: true,
    opacity: 0.9,
    source: { type: "geojson", url: "/data/hydrology/rivers.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#3FA0AA",
      "line-width": 2.5,
    },
  },
  {
    id: "watersheds",
    name: "Watershed boundaries",
    description: "Watershed (DAS) catchment boundaries, one color per catchment. Large fills — use with low opacity.",
    category: "hydrology",
    type: "vector",
    defaultVisible: false,
    opacity: 0.3,
    source: { type: "geojson", url: "/data/hydrology/watersheds.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#1F7A8C",
      "fill-opacity": 0.1,
      "line-color": "#1F7A8C",
      "line-width": 1.5,
      "line-dasharray": [4, 3],
    },
  },
  {
    id: "coastline",
    name: "Coastline",
    description: "Baseline coastline used for distance-to-coast measurement in the AOI analysis panel.",
    category: "coastal",
    type: "vector",
    defaultVisible: false,
    opacity: 0.8,
    source: { type: "geojson", url: "/data/coastal/baseline-coastline.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#B8901E",
      "line-width": 2,
    },
  },
  {
    id: "settlements",
    name: "Settlements",
    description: "Settlement point locations from OSM. Sparse coverage — Taliabu villages are partly unmapped.",
    category: "terrain",
    type: "vector",
    defaultVisible: false,
    opacity: 1,
    source: { type: "geojson", url: "/data/human/settlements.geojson" },
    layerType: "point",
    paint: {
      "circle-radius": 5,
      "circle-color": "#F7F8F1",
      "circle-stroke-color": "#14231D",
      "circle-stroke-width": 1.5,
    },
  },
  {
    id: "settlement-areas",
    name: "Settlement areas",
    description: "Built-up area polygons. Fallback for village footprints where OSM points are missing.",
    category: "terrain",
    type: "vector",
    defaultVisible: false,
    opacity: 0.35,
    source: { type: "geojson", url: "/data/human/settlement-areas.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#C98B55",
      "fill-opacity": 0.18,
      "line-color": "#C98B55",
      "line-width": 1,
    },
  },
  {
    id: "admin-boundary",
    name: "Administrative boundary",
    sub: "Kab. Pulau Taliabu",
    description: "Official administrative boundary of Kabupaten Pulau Taliabu (BIG Satu Peta / RBI).",
    category: "administrative",
    type: "vector",
    defaultVisible: false,
    opacity: 0.6,
    source: { type: "geojson", url: "/data/boundaries/administrative-boundaries.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#3E4C44",
      "line-width": 2,
      "line-dasharray": [6, 3],
    },
  },

  {
    id: "scl",
    name: "SCL",
    sub: "Scene classification · diagnostic",
    description: "Per-pixel quality labels from Sen2Cor. Diagnostic only — not a land-cover map: SCL 5 (bare soil) does not mean mining, SCL 4 (vegetation) is not an inventory.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "scl" },
    legend: [
      { label: "No data", color: "#000000" },
      { label: "Saturated", color: "#FF0000" },
      { label: "Dark area", color: "#2F2F2F" },
      { label: "Cloud shadow", color: "#643200" },
      { label: "Vegetation", color: "#00A000" },
      { label: "Bare soil", color: "#FFE65A" },
      { label: "Water", color: "#0000FF" },
      { label: "Unclassified", color: "#808080" },
      { label: "Cloud medium", color: "#C0C0C0" },
      { label: "Cloud high", color: "#FFFFFF" },
      { label: "Cirrus", color: "#64C8FF" },
      { label: "Snow/ice", color: "#FF96FF" },
    ],
  },
  {
    id: "ndvi",
    name: "NDVI",
    sub: "Vegetation · B08, B04",
    description: "Vegetation greenness index. Same palette as Copernicus Browser. Displayed raw — clouds stay visible; the map chip \"cloud mask\" removes cloud/shadow pixels.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "ndvi", maskable: true },
    legend: [
      { label: "low → high", color: "linear-gradient(90deg,#DBDBDB,#FAFACC,#80B347,#004500)" },
    ],
  },
  {
    id: "ndwi",
    name: "NDWI",
    sub: "Water · B03, B08",
    description: "Open-water index (McFeeters). Green = negative (dry), blue = positive (water). Cloud shadow can read as water — use the cloud mask for interpretation.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "ndwi", maskable: true },
    legend: [
      { label: "dry → water", color: "linear-gradient(90deg,#008000,#FFFFFF,#0000CC)" },
    ],
  },
  {
    id: "mndwi",
    name: "MNDWI",
    sub: "Modified water · B03, B11",
    description: "Modified water index using SWIR (B11) — separates water better than NDWI in turbid or shallow coastal water. Not a standard Copernicus Browser product.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "mndwi", maskable: true },
    legend: [
      { label: "land → water", color: "linear-gradient(90deg,#B38033,#D9D1BF,#8CBFD1,#0D4DA6,#001A73)" },
    ],
  },
  {
    id: "false-color",
    name: "False Color",
    sub: "Analysis · B08, B04, B03",
    description: "NIR composite: vegetation appears red, water dark, bare ground cyan-grey. Useful to spot clear-cuts and burnt scars at a glance.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "false-color", maskable: true },
    legend: [{ label: "Vegetation → red", color: "#C8372D" }],
  },
  {
    id: "bare-soil",
    name: "SWIR",
    sub: "Bare soil/analysis · B12, B11, B04",
    description: "Copernicus Browser SWIR composite with highlight compression. Brightens bare soil, quarry faces and haul roads against forest.",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "bare-soil" },
    legend: [{ label: "Bare soil / built-up", color: "#B38033" }],
  },
  {
    id: "sar",
    name: "SAR (Sentinel-1)",
    sub: "VV, VH · cloud-penetrating",
    description: "Radar backscatter, unaffected by clouds. Tropical forest sits at the sensor noise floor — single-date texture is noisy; interpret diagnostically, not as change.",
    category: "satellite",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "sar" },
  },
];
