import type { MapLayerDefinition } from "@/shared/types/layers";

export const staticLayers: MapLayerDefinition[] = [
  {
    id: "mining-iup",
    name: "Permit boundaries",
    sub: "ESDM / MOMI",
    category: "mining",
    type: "vector",
    defaultVisible: true,
    opacity: 1,
    source: { type: "geojson", url: "/data/mining/iup.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#B4652A",
      "fill-opacity": 0.18,
      "line-color": "#B4652A",
      "line-width": 2,
      "line-dasharray": [5, 3],
    },
  },
  {
    id: "rivers",
    name: "Rivers & watershed",
    category: "hydrology",
    type: "vector",
    defaultVisible: true,
    opacity: 0.9,
    source: { type: "geojson", url: "/data/hydrology/rivers.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#3FA0AA",
      "line-width": 2.5,
    },
  },
  {
    id: "watersheds",
    name: "Watershed boundaries",
    category: "hydrology",
    type: "vector",
    defaultVisible: false,
    opacity: 0.3,
    source: { type: "geojson", url: "/data/hydrology/watersheds.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#1F7A8C",
      "fill-opacity": 0.1,
      "line-color": "#1F7A8C",
      "line-width": 1.5,
      "line-dasharray": [4, 3],
    },
  },
  {
    id: "coastline",
    name: "Coastline",
    category: "coastal",
    type: "vector",
    defaultVisible: false,
    opacity: 0.8,
    source: { type: "geojson", url: "/data/coastal/baseline-coastline.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#B8901E",
      "line-width": 2,
    },
  },
  {
    id: "settlements",
    name: "Settlements",
    category: "terrain",
    type: "vector",
    defaultVisible: false,
    opacity: 1,
    source: { type: "geojson", url: "/data/human/settlements.geojson" },
    layerType: "point",
    paint: {
      "circle-radius": 5,
      "circle-color": "#F7F8F1",
      "circle-stroke-color": "#14231D",
      "circle-stroke-width": 1.5,
    },
  },
  {
    id: "settlement-areas",
    name: "Settlement areas",
    category: "terrain",
    type: "vector",
    defaultVisible: false,
    opacity: 0.35,
    source: { type: "geojson", url: "/data/human/settlement-areas.geojson" },
    layerType: "fill",
    paint: {
      "fill-color": "#C98B55",
      "fill-opacity": 0.18,
      "line-color": "#C98B55",
      "line-width": 1,
    },
  },
  {
    id: "admin-boundary",
    name: "Administrative boundary",
    sub: "Kab. Pulau Taliabu",
    category: "administrative",
    type: "vector",
    defaultVisible: false,
    opacity: 0.6,
    source: { type: "geojson", url: "/data/boundaries/administrative-boundaries.geojson" },
    layerType: "line",
    paint: {
      "line-color": "#3E4C44",
      "line-width": 2,
      "line-dasharray": [6, 3],
    },
  },

  {
    id: "ndvi",
    name: "NDVI",
    sub: "Vegetation · B08, B04",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "ndvi" },
  },
  {
    id: "ndwi",
    name: "NDWI",
    sub: "Water · B03, B08",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "ndwi" },
  },
  {
    id: "mndwi",
    name: "MNDWI",
    sub: "Modified water · B03, B11",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "mndwi" },
  },
  {
    id: "false-color",
    name: "False Color",
    sub: "Analysis · B08, B04, B03",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "false-color" },
  },
  {
    id: "bare-soil",
    name: "Bare Soil",
    sub: "Bare soil · B12, B08A, B04",
    category: "environment",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "bare-soil" },
  },
  {
    id: "sar",
    name: "SAR (Sentinel-1)",
    sub: "VV, VH · cloud-penetrating",
    category: "satellite",
    type: "raster",
    defaultVisible: false,
    opacity: 0.85,
    source: { type: "raster", evalscriptKey: "sar" },
  },
];
